name: flutter_watch_os_connectivity
description: A plugin that provides a wrapper that enables Flutter apps to communicate with apps running on WatchOS.
version: 1.0.1
homepage: https://github.com/ssttonn/flutter_smart_watch/tree/master/flutter_watch_os_connectivity

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_smart_watch_platform_interface: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        package: com.sstonn.flutter_watch_os_connectivity
        pluginClass: FlutterWatchOsConnectivityPlugin
        dartPluginClass: FlutterWatchOsConnectivity